### PR TITLE
FIX: `error: attribute 'tarball' missing`

### PR DESCRIPTION
**Pull request by peter-workday**

### CODE REVIEW

**Comment by peter-workday** [comment]
i am now getting new error not related to this, so i can not fully test :(

**Comment by adisbladis** [comment]
Why was this PR closed? Is this an issue?

**Comment by peter-workday** [comment]
i found another issue, will need some more work and testing.
________________________________

**Comment by peter-workday** [comment]
with this "fix":
```
⋊> ./make run-test
building '/nix/store/nb4w7ry04ffsixvhs24pwfzf8c8cvyz9-TrustedKeyService-shrinkwrap-0.1.0.drv'...
unpacking 'https://registry.npmjs.org/@0xproject/abi-gen/-/abi-gen-1.0.7.tgz'...
error: unable to download 'https://registry.npmjs.org/sane-subproviders/-/sane-subproviders-1.0.8.tgz': HTTP error 404
(use '--show-trace' to show detailed location information)
```
without it:
```
⋊> ./make run-test
error: attribute 'tarball' missing, at /nix/store/008lj586fmhxzvjrp8lkr6y2cknx0yr1-source/default.nix:158:17
(use '--show-trace' to show detailed location information)
```

shrinkwrap:
```
⋊> cat shrinkwrap.yaml | grep 'abi-gen\|sane-subproviders'
  sane-subproviders: ghe.enterprise.com/trustedkey/sane-subproviders/3a9e16677356b41b4adbb642ef4c151f5aa47cf9
  ghe.enterprise.com/trustedkey/0x-abi-gen/46d4b083cbd6d1bd31381654f1da9519e4315f5b:
    name: '@0xproject/abi-gen'
      repo: 'https://ghe.enterprise.com/trustedkey/0x-abi-gen'
  ghe.enterprise.com/trustedkey/sane-subproviders/3a9e16677356b41b4adbb642ef4c151f5aa47cf9:
    name: sane-subproviders
      repo: 'https://ghe.enterprise.com/trustedkey/sane-subproviders'
      '@0xproject/abi-gen': ghe.enterprise.com/trustedkey/0x-abi-gen/46d4b083cbd6d1bd31381654f1da9519e4315f5b
      sane-subproviders: ghe.enterprise.com/trustedkey/sane-subproviders/3a9e16677356b41b4adbb642ef4c151f5aa47cf9
  sane-subproviders: 'git+https://ghe.enterprise.com/trustedkey/sane-subproviders'
```

i might need to change it to ssh, only have global overlay for ssh yet, could also expose the enterprise git token during build i guess?
```
⋊> cat ~/.config/fish/config.fish
set -xg NIX_PATH ssh-config-file=/etc/ssh/ssh_config ssh-auth-sock=$SSH_AUTH_SOCK $NIX_PATH
```

**Pull request closed without merging**
